version: '3.8'

services:
  # Servicio para la aplicación
  app:
    image: node:14
    container_name: my-app-container
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: "npm start"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=tailwind

  # Servicio para MySQL
  db:
    image: mysql:5.7
    container_name: my-db-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # Configuración comentada para PostgreSQL
  # postgres:
  #   image: postgres:13
  #   container_name: my-postgres-container
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: rootpassword
  #     POSTGRES_DB: mydatabase
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

# Volúmenes para persistencia de datos
volumes:
  mysql-data:
  # postgres-data:

# Redes para conectar los servicios
networks:
  app-network:
    driver: bridge
